services:
  equitymap:
    image: atddocker/dts-equity-analysis-zones:production
    restart: unless-stopped
    ports:
      - 8050:8050
    volumes:
      - .:/root/app
    command: ["python", "eaz_comparison_tool.py"]
